name: 🐛 Bugfix
description: Corrección de errores o regresiones
title: 'fix: '
body:
  - type: textarea
    id: problema
    attributes:
      label: 🐞 Qué problema resuelve
      description: ¿Qué problema se resolvió y cómo? Agrega capturas o pasos si ayuda a entender el fix.
      required: true

  - type: textarea
    id: solucion
    attributes:
      label: 🔧 Qué hiciste
      description: Explica los cambios aplicados para resolver el problema.
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist
      options:
        - label: Cambios probados localmente
        - label: El bug ya no ocurre
        - label: Se mantuvo la funcionalidad existente
        - label: Se agregó test que lo cubra (si aplica)
        - label: Se actualizó la documentación (si aplica)
        - label: Pasa `lint`, `format` y `test`
        - label: Rama actualizada con `develop`

  - type: textarea
    id: notas
    attributes:
      label: 📝 Notas adicionales
      description: Cualquier detalle técnico o decisión tomada que deba conocer el equipo
