name: ✨ Feature
description: Nuevas funcionalidades o mejoras
title: 'feat: '
body:
  - type: textarea
    id: descripcion
    attributes:
      label: 📋 Descripción
      description: ¿Qué funcionalidad se agrega o mejora? Agrega capturas o GIFs si ayuda a entender el cambio.
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist
      options:
        - label: Cambios probados localmente
        - label: Tests agregados o modificados (si aplica)
        - label: Se actualizó la documentación (si aplica)
        - label: Pasa `lint`, `format` y `test`
        - label: Rama actualizada con `develop`

  - type: textarea
    id: notas
    attributes:
      label: 📝 Notas adicionales
      description: Cualquier detalle técnico o decisión tomada que deba conocer el equipo
