name: 🚑 Hotfix
description: Correcciones urgentes o errores críticos
title: 'hotfix: '
body:
  - type: textarea
    id: problema
    attributes:
      label: 💥 Qué problema crítico soluciona
      description: ¿Qué error crítico se solucionó y por qué era urgente? Agrega capturas o contexto si ayuda a entenderlo.
      required: true

  - type: textarea
    id: solucion
    attributes:
      label: ⏱ Urgencia y solución aplicada
      description: Explica por qué se debe aplicar rápido y cómo se resolvió.
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist
      options:
        - label: Cambios probados localmente y/o en entorno real
        - label: El error crítico ya no ocurre
        - label: Se mantuvo la funcionalidad existente
        - label: Se agregó test que lo cubra (si aplica)
        - label: Se actualizó la documentación (si aplica)
        - label: Pasa `lint`, `format` y `test`
        - label: Rama actualizada con `develop`

  - type: textarea
    id: notas
    attributes:
      label: 📝 Notas adicionales
      description: Cualquier detalle técnico o decisión tomada que deba conocer el equipo
